# .goreleaser.yml
project_name: gweet

before:
  hooks:
    - go mod tidy
    - go test -v ./...

builds:
  - id: gweet
    binary: gweet
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64

archives:
  - id: gweet
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
      - 'Merge pull request'
      - 'Merge branch'

release:
  github:
    owner: skorokithakis
    name: gweet
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## Gweet v{{ .Version }}
    
    Simple message queue for IoT devices.
    
  footer: |
    **Full Changelog**: https://github.com/skorokithakis/gweet/compare/{{ .PreviousTag }}...{{ .Tag }}